const KEY='myhub-v2-data';
const AUTH_KEY='myhub-v2-auth';
const defaults={profile:{name:'MyHub User',info:'MyHub V2',photo:''},home:{title:'WELCOME TO MyHub V2',subtitle:'A small space for everyday things.'},animations:true,locked:{},password:'',notes:[],todos:[],finance:[],calendar:[],games:[{name:'Free Fire',link:'https://ff.garena.com/',icon:'🎮'},{name:'Mobile Legends',link:'https://m.mobilelegends.com/',icon:'⚔️'},{name:'Magic Chess',link:'https://m.mobilelegends.com/',icon:'♟️'},{name:'Block Blast',link:'https://blockblast.com/',icon:'🧩'}],music:[{title:'Spotify Track 1',link:'https://open.spotify.com/track/3rPtS4nfpy7PsARctAWpzd'},{title:'Spotify Track 2',link:'https://open.spotify.com/track/48BWWtyjFE2le9sIqJitoL'},{title:'Spotify Track 3',link:'https://open.spotify.com/track/3AAAGS7iM1ekDywqdYMJG2'},{title:'Spotify Track 4',link:'https://open.spotify.com/track/5gkTGkjFB5wAd3mSBEcQPY'}],gallery:[]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(defaults);
let auth=JSON.parse(localStorage.getItem(AUTH_KEY)||'null');
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function saveAuth(){localStorage.setItem(AUTH_KEY,JSON.stringify(auth))}
const nav=[['home','Home'],['search','Search'],['contact','Contact'],['settings','Settings']];
let current='home';
const $=s=>document.querySelector(s);function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function fold(root=document){if(!data.animations)return;root.querySelectorAll('.fold-text').forEach(el=>{if(el.dataset.folded)return;let text=el.textContent;el.textContent='';[...text].forEach((c,i)=>{let s=document.createElement('span');s.className='fold-char';s.textContent=c===' '?'\u00a0':c;s.style.animationDelay=i*.025+'s';el.appendChild(s)});el.dataset.folded='1'})}
function icon(name){return `<i class="fa-solid ${name}"></i>`}
function renderNav(){}
function renderDrawer(){let items=[['game','fa-gamepad','Game'],['calendar','fa-calendar-days','Kalender'],['notes','fa-note-sticky','Catatan'],['todo','fa-list-check','Tugas'],['music','fa-music','Musik'],['finance','fa-wallet','Keuangan'],['contact','fa-comments','Kontak'],['profile','fa-user','Akun'],['locked','fa-lock','Aplikasi Terkunci'],['settings','fa-gear','Pengaturan']];$('#drawerMenu').innerHTML=items.map(([id,ic,l])=>`<button class="${id==='settings'?'settings':''}" onclick="closeDrawer();go('${id}')">${icon(ic)}<span>${l}</span></button>`).join('');$('#accountName').textContent=data.profile.name||'Account';$('#accountInfo').textContent=auth?.email||data.profile.info||'MyHub V2';$('#drawerMenu').insertAdjacentHTML('beforeend',`<button onclick="closeDrawer();logout()">${icon('fa-right-from-bracket')}<span>Keluar Akun</span></button>`)}
function renderDock(){let items=[['home','fa-house','Home'],['quickaccess','fa-bolt','Quick Access'],['profile','fa-user','Account'],['settings','fa-gear','Settings']];$('#dock').innerHTML=items.map(([id,ic,label])=>`<div class="dock-item-wrap"><span class="dock-label">${label}</span><button class="dock-item" onclick="${id==='quickaccess'?'openQuickAccess()':`go('${id}')`}"><span class="dock-icon">${icon(ic)}</span></button></div>`).join('');document.querySelectorAll('.dock-item').forEach((el,i)=>el.addEventListener('mousemove',e=>{let r=el.getBoundingClientRect(),d=Math.max(0,1-Math.abs(e.clientX-(r.left+r.width/2))/180);el.style.transform=`scale(${1+d*.42}) translateY(${-d*8}px)`}));document.querySelectorAll('.dock-item').forEach(el=>el.addEventListener('mouseleave',()=>el.style.transform=''))}
function pageHead(t,p){return `<div class="page-head fold-text"><h1>${t}</h1><p>${p}</p></div>`}
function home(){return `<section class="hero hero-home"><div class="hero-content"><h1 class="fold-text">${esc(data.home.title)}</h1><p class="fold-text">${esc(data.home.subtitle)}</p><div class="profile-card-slot">${typeof renderProfileCard==='function'?renderProfileCard(data.profile):''}</div></div></section>`}
function game(){return pageHead('Game','Kumpulan game yang tersedia.')+`<div class="grid">${data.games.map((g,i)=>`<div class="card glass"><div class="feature-icon" style="font-size:38px">${icon(({ 'Free Fire':'fa-fire','Mobile Legends':'fa-shield-halved','Magic Chess':'fa-chess-knight','Block Blast':'fa-cubes-stacked'})[g.name]||'fa-gamepad')}</div><h3 class="fold-text">${esc(g.name)}</h3><button class="btn" onclick="openGame(${i})">Buka</button></div>`).join('')}</div>`}
function simpleList(type,title,desc){let arr=data[type];return pageHead(title,desc)+`<div class="glass card"><div class="form"><input class="input" id="new_${type}" placeholder="Tambah item..."><button class="btn" onclick="addItem('${type}')">Tambah</button></div><div class="list" style="margin-top:14px">${arr.map((x,i)=>`<div class="list-item"><span>${esc(typeof x==='string'?x:x.title||x.text||x.name||'Item')}</span><button class="btn danger" style="float:right" onclick="delItem('${type}',${i})">Hapus</button></div>`).join('')}</div></div>`}
function finance(){return pageHead('Keuangan','Catatan pemasukan dan pengeluaran.')+simpleList('finance','Finance','')}
function search(){return pageHead('Pencarian','Temukan fitur di MyHub V2.')+`<div class="glass card"><div class="form"><input class="input" id="hubSearch" placeholder="Cari fitur..." oninput="filterFeatures(this.value)"></div><div class="grid" id="searchResults">${searchCards('')}</div></div>`}
function searchCards(q){let features=[['Game','game','fa-gamepad'],['Finance','finance','fa-wallet'],['Contact','contact','fa-comments'],['Account','profile','fa-user'],['Notes','notes','fa-note-sticky'],['Todo','todo','fa-list-check'],['Kalender','calendar','fa-calendar-days'],['Music','music','fa-music'],['Settings','settings','fa-gear']];q=(q||'').toLowerCase();return features.filter(x=>x[0].toLowerCase().includes(q)).map(x=>`<button class="card glass" style="text-align:left;color:inherit" onclick="go('${x[1]}')">${icon(x[2])} <span style="margin-left:8px">${x[0]}</span></button>`).join('')||'<p class="muted">Fitur tidak ditemukan.</p>'}
function filterFeatures(q){$('#searchResults').innerHTML=searchCards(q)}
function openQuickAccess(){$('#drawer').classList.add('open');$('#drawerShade').classList.add('open')}
function contact(){return pageHead('Kontak','Hubungi pemilik MyHub V2.')+`<div class="grid"><a class="card glass" style="color:white;text-decoration:none" href="https://wa.me/6283899019848" target="_blank"><h3>WhatsApp 1</h3><p class="muted">083899019848</p></a><a class="card glass" style="color:white;text-decoration:none" href="https://wa.me/6288212424587" target="_blank"><h3>WhatsApp 2</h3><p class="muted">088212424587</p></a></div>`}
function profile(){return pageHead('Akun','Informasi akun pengguna.')+`<div class="glass card"><h2 class="fold-text">${esc(data.profile.name)}</h2><p class="muted">${esc(data.profile.info)}</p></div>`}
function editFitur(){return pageHead('Kelola Fitur','Pilih bagian MyHub yang ingin diubah.')+`<a class="btn back-btn" href="#settings" onclick="event.preventDefault();go('settings')">${icon('fa-arrow-left')} Pengaturan</a><div class="settings-grid edit-feature-list">
<a class="glass card setting-card" href="edit-profil.html"><div class="setting-icon">${icon('fa-user')}</div><div><h3>Edit Profil</h3><p class="muted">Foto, nama, dan info ProfileCard.</p></div><span>${icon('fa-chevron-right')}</span></a>
<a class="glass card setting-card" href="edit-home.html"><div class="setting-icon">${icon('fa-house')}</div><div><h3>Beranda</h3><p class="muted">Ubah judul dan deskripsi beranda.</p></div><span>${icon('fa-chevron-right')}</span></a>
<a class="glass card setting-card" href="edit-game.html"><div class="setting-icon">${icon('fa-gamepad')}</div><div><h3>Game</h3><p class="muted">Atur daftar game.</p></div><span>${icon('fa-chevron-right')}</span></a>
<a class="glass card setting-card" href="edit-music.html"><div class="setting-icon">${icon('fa-music')}</div><div><h3>Musik</h3><p class="muted">Atur koleksi lagu Spotify.</p></div><span>${icon('fa-chevron-right')}</span></a>
<a class="glass card setting-card" href="edit-gallery.html"><div class="setting-icon">${icon('fa-images')}</div><div><h3>Galeri</h3><p class="muted">Kelola foto galeri.</p></div><span>${icon('fa-chevron-right')}</span></a>
<a class="glass card setting-card" href="edit-finance.html"><div class="setting-icon">${icon('fa-wallet')}</div><div><h3>Keuangan</h3><p class="muted">Atur catatan keuangan.</p></div><span>${icon('fa-chevron-right')}</span></a>
<a class="glass card setting-card" href="edit-tampilan.html"><div class="setting-icon">${icon('fa-palette')}</div><div><h3>Tampilan</h3><p class="muted">Atur animasi dan tema halaman.</p></div><span>${icon('fa-chevron-right')}</span></a>
</div>`}
function settings(){return pageHead('Pengaturan','Atur akun, fitur, dan tampilan MyHub V2')+`<div class="settings-grid"><a class="glass card setting-card" href="#edit-fitur" onclick="event.preventDefault();go('edit-fitur')"><div class="setting-icon">${icon('fa-sliders')}</div><div><h3>Kelola Fitur</h3><p class="muted">Ubah isi fitur satu per satu.</p></div><span>${icon('fa-chevron-right')}</span></a><a class="glass card setting-card" href="edit-profil.html"><div class="setting-icon">${icon('fa-user')}</div><div><h3>Edit Profil</h3><p class="muted">Ganti foto, nama, dan info ProfileCard.</p></div><span>${icon('fa-chevron-right')}</span></a><div class="glass card setting-card"><div class="setting-icon">${icon('fa-palette')}</div><div><h3>Tampilan</h3><p class="muted">Tema: ${document.body.classList.contains('light-theme')?'Terang':'Gelap'} · Animasi: ${data.animations?'Aktif':'Nonaktif'}</p></div><button class="btn" onclick="toggleTheme();render()">Ganti</button></div><div class="glass card"><h3>Data</h3><div class="row"><button class="btn danger" onclick="resetData()">Reset semua data</button></div></div></div>`}
function notes(){return simpleList('notes','Catatan','Simpan catatan di perangkat ini.')};function todo(){return simpleList('todos','Tugas','Daftar tugas yang perlu dikerjakan.')};function calendar(){return simpleList('calendar','Kalender','Agenda sederhana.')}
function music(){return pageHead('Musik','Koleksi lagu dari Spotify.')+`<div class="grid">${data.music.map(m=>`<div class="glass card"><h3>${esc(m.title)}</h3><iframe style="border-radius:12px;width:100%" src="https://open.spotify.com/embed/track/${m.link.split('/track/')[1]?.split('?')[0]||''}" height="152" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe></div>`).join('')}</div>`}
function locked(){return pageHead('Aplikasi Terkunci','Pilih fitur yang ingin dilindungi dengan sandi.')+`<div class="glass card"><div class="form"><input class="input" type="password" id="lockPass" placeholder="Buat/ganti sandi"><button class="btn" onclick="setPassword()">Simpan sandi</button><p class="muted">Aktifkan kunci per fitur:</p>${['game','notes','todo','finance','calendar','music'].map(x=>`<label><input type="checkbox" ${data.locked[x]?'checked':''} onchange="toggleLock('${x}',this.checked)"> ${x}</label>`).join('')}</div></div>`}
function renderAuth(hide=false){let root=$('#authRoot');if(hide){root.innerHTML='';return}root.innerHTML=`<main class="auth-screen"><div class="auth-box glass"><div class="auth-logo">${icon('fa-user-lock')}</div><h1 class="fold-text">Masuk ke MyHub V2</h1><p>Masuk dulu untuk membuka beranda dan semua fitur.</p><form class="form" onsubmit="event.preventDefault();login()"><input class="input" id="authEmail" type="email" placeholder="Email Gmail" required><input class="input" id="authPass" type="password" placeholder="Password" minlength="4" required><button class="btn" type="submit">${icon('fa-right-to-bracket')} Masuk</button></form><div class="auth-switch">Belum punya akun? <button class="link-btn" onclick="showRegister()">Buat akun</button></div></div></main>`;fold(root)}
function showRegister(){let root=$('#authRoot');root.innerHTML=`<main class="auth-screen"><div class="auth-box glass"><div class="auth-logo">${icon('fa-user-plus')}</div><h1 class="fold-text">Buat Akun</h1><p>Akun disimpan di perangkat ini.</p><form class="form" onsubmit="event.preventDefault();register()"><input class="input" id="regName" placeholder="Nama" required><input class="input" id="regEmail" type="email" placeholder="Email Gmail" required><input class="input" id="regPass" type="password" placeholder="Password" minlength="4" required><button class="btn" type="submit">${icon('fa-user-plus')} Buat Akun</button></form><div class="auth-switch">Sudah punya akun? <button class="link-btn" onclick="renderAuth()">Masuk</button></div></div></main>`;fold(root)}
function register(){let name=$('#regName').value.trim(),email=$('#regEmail').value.trim(),password=$('#regPass').value;if(!email.toLowerCase().endsWith('@gmail.com')){toast('Gunakan email Gmail');return}auth={name,email,password};data.profile.name=name;data.profile.info=email;saveAuth();save();render();toast('Akun berhasil dibuat')}
function login(){let email=$('#authEmail').value.trim(),password=$('#authPass').value;if(!auth||email.toLowerCase()!==auth.email.toLowerCase()||password!==auth.password){toast('Email atau password salah');return}render();toast('Berhasil masuk')}
function logout(){auth=null;localStorage.removeItem(AUTH_KEY);current='home';render()}
function render(){
 if(!auth){renderAuth();$('#app').innerHTML='';$('#gooeyNav').innerHTML='';$('#dock').innerHTML='';return}
 renderAuth(true);renderNav();renderDrawer();renderDock();let pages={home,search,game,finance,contact,profile,settings,'edit-fitur':editFitur,notes,todo,calendar,music,locked};$('#app').innerHTML=(pages[current]||home)();fold($('#app'));if(typeof initProfileCards==='function')initProfileCards($('#app'));
}
function go(id){if(data.locked[id]&&id!=='locked'){let p=prompt('Masukkan sandi untuk membuka '+id);if(p!==data.password){toast('Sandi salah');return}}current=id;render();window.scrollTo({top:0,behavior:'smooth'})}
function addItem(type){let v=$('#new_'+type).value.trim();if(!v)return;data[type].push(type==='finance'?{title:v}:v);save();render();toast('Ditambahkan')};function delItem(type,i){data[type].splice(i,1);save();render()}
function saveSettings(){data.profile.name=$('#setName').value;data.profile.info=$('#setInfo').value;data.home.title=$('#setTitle').value;data.home.subtitle=$('#setSub').value;data.animations=$('#setAnim').checked;save();render();toast('Pengaturan tersimpan')}
function toggleAppearanceSettings(){data.animations=!data.animations;save();render();toast('Animasi diperbarui')}
function setPassword(){let p=$('#lockPass').value.trim();if(p.length<4){toast('Sandi minimal 4 karakter');return}data.password=p;save();toast('Sandi tersimpan')};function toggleLock(k,v){data.locked[k]=v;save()};function resetData(){if(confirm('Reset semua data?')){data=structuredClone(defaults);save();render()}}
function openGame(i){let g=data.games[i];if(g.link)window.open(g.link,'_blank')}
function esc(x=''){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(x=''){return esc(x)}
function closeDrawer(){$('#drawer').classList.remove('open');$('#drawerShade').classList.remove('open')}
function toggleTheme(){document.body.classList.toggle('light-theme');const light=document.body.classList.contains('light-theme');localStorage.setItem('myhub-theme',light?'light':'dark');const b=$('#themeBtn');if(b)b.innerHTML=icon(light?'fa-moon':'fa-sun')}
$('#searchBtn').onclick=()=>go('search');
$('#themeBtn').onclick=toggleTheme;
$('#menuBtn').onclick=()=>{$('#drawer').classList.add('open');$('#drawerShade').classList.add('open')};
$('#closeDrawer').onclick=closeDrawer;$('#drawerShade').onclick=closeDrawer;
if(localStorage.getItem('myhub-theme')==='light'){document.body.classList.add('light-theme');$('#themeBtn').innerHTML=icon('fa-moon')}
if(location.hash==='#edit-fitur')current='edit-fitur';render();
